spring:
  datasource:
    url: jdbc:postgresql://localhost:5231/bookstore
    username: sa
    password: password
  jpa:
    show-sql: true
    generate-ddl: true
  flyway:
    baseline-on-migrate: true
    validate-on-migrate: true
  sql:
    init:
      mode: always  # enable init for non-embedded database
