spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  jpa:
    database: h2
    show-sql: true
    generate-ddl: true
  flyway:
    baseline-on-migrate: true
    validate-on-migrate: true
